// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	LastUpdatedOn        *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated_on,json=lastUpdatedOn,proto3" json:"last_updated_on,omitempty"`
	Location             *_struct.Value       `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *User) GetLastUpdatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdatedOn
	}
	return nil
}

func (m *User) GetLocation() *_struct.Value {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "models.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xad, 0xa1, 0x19, 0x11, 0x61, 0x0f, 0x12, 0xa2, 0x62, 0xf1, 0xd4, 0x53, 0x0a,
	0xf5, 0xe4, 0xd5, 0x07, 0xb0, 0x10, 0xac, 0xd7, 0xb2, 0x4d, 0xa6, 0x25, 0xb0, 0xd9, 0x09, 0xbb,
	0xb3, 0x0f, 0xe2, 0x1b, 0x4b, 0x66, 0xdd, 0x1e, 0xf4, 0xd0, 0xe3, 0xfc, 0xdf, 0xff, 0x0d, 0x3f,
	0x40, 0xf0, 0xe8, 0xea, 0xd1, 0x11, 0x93, 0xca, 0x07, 0xea, 0xd0, 0xf8, 0xea, 0xf9, 0x44, 0x74,
	0x32, 0xb8, 0x96, 0xf4, 0x10, 0x8e, 0x6b, 0xee, 0x07, 0xf4, 0xac, 0x87, 0x31, 0x16, 0xab, 0xc7,
	0xbf, 0x05, 0xcf, 0x2e, 0xb4, 0x1c, 0xe9, 0xcb, 0xf7, 0x0c, 0xe6, 0x3b, 0x8f, 0x4e, 0x55, 0xb0,
	0x98, 0xbe, 0x5b, 0x3d, 0x60, 0x99, 0x2d, 0xb3, 0x55, 0xd1, 0x9c, 0x6f, 0xf5, 0x04, 0x70, 0xec,
	0x9d, 0xe7, 0xbd, 0xd0, 0x99, 0xd0, 0x42, 0x92, 0x8f, 0x09, 0x3f, 0x40, 0x61, 0x74, 0xa2, 0x57,
	0xd1, 0x9d, 0x02, 0x81, 0x6f, 0x00, 0xad, 0x43, 0xcd, 0xd8, 0xed, 0xc9, 0x96, 0xf3, 0x65, 0xb6,
	0xba, 0xd9, 0x54, 0x75, 0xdc, 0x54, 0xa7, 0x4d, 0xf5, 0x67, 0x1a, 0xdd, 0x14, 0xbf, 0xed, 0xad,
	0x55, 0xef, 0x70, 0x27, 0x7f, 0xc3, 0xd8, 0x25, 0xff, 0xfa, 0xa2, 0x7f, 0x3b, 0x29, 0xbb, 0x68,
	0x6c, 0xad, 0xda, 0xc0, 0xc2, 0x50, 0xab, 0xb9, 0x27, 0x5b, 0xe6, 0x22, 0xdf, 0xff, 0x93, 0xbf,
	0xb4, 0x09, 0xd8, 0x9c, 0x7b, 0x87, 0x5c, 0xc8, 0xeb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71,
	0x7b, 0xaf, 0x99, 0x6f, 0x01, 0x00, 0x00,
}
