// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	LastUpdatedOn        *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated_on,json=lastUpdatedOn,proto3" json:"last_updated_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b751c8b51d21fe45, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *User) GetLastUpdatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdatedOn
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "models.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_b751c8b51d21fe45) }

var fileDescriptor_user_b751c8b51d21fe45 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x19, 0xad, 0xc5, 0x5c, 0x11, 0x21, 0xab, 0x32, 0x22, 0x14, 0x57, 0x5d, 0x25, 0xa0,
	0x2b, 0x71, 0xe7, 0x03, 0x58, 0x28, 0x76, 0x5d, 0x32, 0x9d, 0xdb, 0x38, 0x90, 0xe4, 0x86, 0xfc,
	0x2c, 0x7c, 0x58, 0xdf, 0x45, 0x92, 0x31, 0xba, 0xec, 0x2e, 0xb9, 0xdf, 0xf9, 0x0e, 0x07, 0x20,
	0x47, 0x0c, 0xc2, 0x07, 0x4a, 0xc4, 0x97, 0x96, 0x46, 0x34, 0xb1, 0x7f, 0xd5, 0x53, 0xfa, 0xcc,
	0x83, 0x38, 0x92, 0x95, 0x9a, 0x8c, 0x72, 0x5a, 0xd6, 0xc0, 0x90, 0x4f, 0xd2, 0xa7, 0x2f, 0x8f,
	0x51, 0xa6, 0xc9, 0x62, 0x4c, 0xca, 0xfa, 0xff, 0xd7, 0x5c, 0xf2, 0xf8, 0xdd, 0xc1, 0x62, 0x1f,
	0x31, 0xf0, 0x1e, 0xae, 0x4b, 0xb7, 0x53, 0x16, 0x57, 0xdd, 0xba, 0xdb, 0xb0, 0xdd, 0xdf, 0x9f,
	0x3f, 0x00, 0x9c, 0xa6, 0x10, 0xd3, 0xa1, 0xd2, 0x8b, 0x4a, 0x59, 0xbd, 0xbc, 0x17, 0x7c, 0x0f,
	0xcc, 0xa8, 0x46, 0x2f, 0x67, 0xb7, 0x1c, 0x2a, 0x7c, 0x01, 0x38, 0x06, 0x54, 0x09, 0xc7, 0x03,
	0xb9, 0xd5, 0x62, 0xdd, 0x6d, 0x6e, 0x9e, 0x7a, 0xa1, 0x89, 0xb4, 0x41, 0xd1, 0x76, 0x8a, 0x8f,
	0x36, 0x6b, 0xc7, 0x7e, 0xd3, 0x5b, 0xc7, 0xdf, 0xe0, 0xae, 0xf6, 0x66, 0x3f, 0x36, 0xff, 0xea,
	0xac, 0x7f, 0x5b, 0x94, 0xfd, 0x6c, 0x6c, 0xdd, 0xb0, 0xac, 0x91, 0xe7, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x89, 0xfc, 0xd8, 0x7e, 0x39, 0x01, 0x00, 0x00,
}
